import React, { useEffect, useRef, useState } from 'react';
import { Activity, ChevronDown, ChevronRight, Gavel, ZoomIn, ZoomOut } from 'lucide-react';
import { Link } from 'react-router-dom';
import * as api from '../api/client';

export function useTournamentData() {
  const [tournaments, setTournaments] = useState([]);
  const [selectedTid, setSelectedTid] = useState('');
  const [data, setData] = useState(null);
  const [auction, setAuction] = useState(null);
  const socket = useRef(null);
  const load = async tid => {
    try {
      const next = await api.getTournamentFull(tid);
      setData(next);
      const live = await api.getPublicAuction(tid).catch(() => null);
      setAuction(live?.status === 'live' ? live : null);
    } catch (error) { console.error('Failed to load tournament:', error); }
  };
  useEffect(() => { api.getTournaments().then(items => { setTournaments(items); const savedTid = localStorage.getItem('selectedTournamentId'); const initialTid = items.some(item => item.id === savedTid) ? savedTid : items[0]?.id || ''; if (initialTid) { setSelectedTid(initialTid); localStorage.setItem('selectedTournamentId', initialTid); } }); }, []);
  useEffect(() => { if (selectedTid) load(selectedTid); }, [selectedTid]);
  useEffect(() => { socket.current = api.connectLiveScores(message => { if (selectedTid && ['score_update', 'scorecard_created', 'scorecard_completed', 'scorecard_updated', 'tournament_updated'].includes(message.type)) load(selectedTid); }); return () => socket.current?.close(); }, [selectedTid]);
  useEffect(() => { if (!selectedTid) return undefined; const timer = setInterval(() => api.getPublicAuction(selectedTid).then(next => setAuction(next?.status === 'live' ? next : null)).catch(() => setAuction(null)), 5000); return () => clearInterval(timer); }, [selectedTid]);
  const selectTournament = tid => { setSelectedTid(tid); localStorage.setItem('selectedTournamentId', tid); };
  return { tournaments, selectedTid, setSelectedTid: selectTournament, data, auction };
}

function PageFrame({ title, subtitle, children, context }) { return <div className="public-page animate-fade-in"><div className="page-topline"><div><p className="eyebrow">TOURNAMENT VIEW</p><h1>{title}</h1><p className="dashboard-subtitle">{subtitle}</p></div><Link to="/" className="btn btn-outline">Back to hub</Link></div>{context}{children}</div>; }
function usePublicPage(title, subtitle) { const state = useTournamentData(); if (!state.data) return { state, context: null, page: <PageFrame title={title} subtitle={subtitle}><p className="empty-state">{state.tournaments.length ? 'Loading tournament...' : 'No tournaments available.'}</p></PageFrame> }; return { state, context: null, page: null }; }
function details(data) { const teams = data.teams || [], events = data.events || [], scorecards = data.scorecards || []; return { teams, events, scorecards, players: data.players || [], auction: data.auction, fixtures: [...(data.fixtures || [])].sort((a, b) => new Date(a.date_time || 0) - new Date(b.date_time || 0)), getTeam: id => teams.find(team => team.id === id)?.name || id }; }

export function SchedulePage() { const { state, page, context } = usePublicPage('Schedule', 'Upcoming fixtures and match details.'); if (page) return page; const d = details(state.data); return <PageFrame title="Schedule" subtitle="Upcoming fixtures and match details." context={context}><FixtureList {...d} fixtures={d.fixtures.filter(f => f.status !== 'completed')} empty="No upcoming matches scheduled." /></PageFrame>; }
export function ResultsPage() { const { state, page, context } = usePublicPage('Results', 'Completed matches and event scores.'); if (page) return page; const d = details(state.data); return <PageFrame title="Results" subtitle="Completed matches and event scores." context={context}><FixtureList {...d} fixtures={d.fixtures.filter(f => f.status === 'completed')} results empty="No completed matches yet." /></PageFrame>; }
function FixtureList({ fixtures, events, scorecards, getTeam, results, empty }) { const [expanded, setExpanded] = useState({}); if (!fixtures.length) return <p className="empty-state">{empty}</p>; return <div className="table-container"><table><thead><tr><th>Match</th><th>Type</th><th>{results ? 'Result' : 'Date & Time'}</th><th>Status</th></tr></thead><tbody>{fixtures.map(f => { const scores = scorecards.filter(s => s.fixture_id === f.id && s.status === 'completed'); const first = scores.filter(s => s.winner === 'team1').reduce((sum, s) => sum + (s.event_points || 0), 0); const second = scores.filter(s => s.winner === 'team2').reduce((sum, s) => sum + (s.event_points || 0), 0); const open = expanded[f.id]; return <React.Fragment key={f.id}><tr className="hoverable-row" onClick={() => setExpanded(old => ({ ...old, [f.id]: !old[f.id] }))}><td className="match-name">{open ? <ChevronDown size={16} /> : <ChevronRight size={16} />}{getTeam(f.team1_id)} <span>vs</span> {getTeam(f.team2_id)}</td><td style={{ textTransform: 'capitalize' }}>{(f.match_type || '').replace('_', ' ')}</td><td>{results ? `${first} - ${second}` : f.date_time ? new Date(f.date_time).toLocaleString(undefined, { dateStyle: 'short', timeStyle: 'short' }) : 'Not Scheduled'}</td><td><span className={`badge badge-${f.status.replace('_', '-')}`}>{f.status.replace('_', ' ')}</span></td></tr>{open && <tr><td colSpan="4"><FixtureEvents fixture={f} events={events} scorecards={scorecards} /></td></tr>}</React.Fragment>; })}</tbody></table></div>; }
function FixtureEvents({ fixture, events, scorecards }) { return <div className="fixture-events">{events.map(event => { const score = scorecards.find(s => s.fixture_id === fixture.id && s.event_id === event.id); return <div className="fixture-event" key={event.id}><strong>{event.name}</strong><span>{[score?.team1_player1, score?.team1_player2].filter(Boolean).join(' & ') || 'TBD'}</span><b>{score?.status === 'completed' ? (score.sets || []).map(s => `${s.team1_score}-${s.team2_score}`).join(' | ') : score?.status === 'in_progress' ? 'LIVE' : 'Upcoming'}</b><span>{[score?.team2_player1, score?.team2_player2].filter(Boolean).join(' & ') || 'TBD'}</span></div>; })}</div>; }

export function StandingsPage() { const { state, page, context } = usePublicPage('Standings', 'Track teams, points, and group rankings.'); if (page) return page; const { teams, fixtures, events, scorecards } = details(state.data); const table = calculateStandings(teams, fixtures, events, scorecards); const groups = [...new Set(teams.map(t => t.group).filter(Boolean))]; return <PageFrame title="Standings" subtitle="Track teams, points, and group rankings." context={context}>{groups.length ? groups.map(group => <section className="standings-group" key={group}><h3>Group {group}</h3><StandingsTable rows={table.filter(row => row.group === group)} /></section>) : <StandingsTable rows={table} />}</PageFrame>; }
function calculateStandings(teams, fixtures, events, scorecards) { const rows = Object.fromEntries(teams.map(t => [t.id, { id: t.id, name: t.name, group: t.group, played: 0, won: 0, lost: 0, points: 0, eventDiff: 0, setPointDiff: 0 }])); fixtures.filter(f => f.status === 'completed').forEach(f => { const one = rows[f.team1_id], two = rows[f.team2_id], scores = scorecards.filter(s => s.fixture_id === f.id && s.status === 'completed'); if (!one || !two || !scores.length) return; let a = 0, b = 0, diff = 0; scores.forEach(s => { const p = s.event_points ?? events.find(e => e.id === s.event_id)?.points ?? 0; if (s.winner === 'team1') a += p; if (s.winner === 'team2') b += p; (s.sets || []).forEach(set => { diff += (set.team1_score || 0) - (set.team2_score || 0); }); }); one.played++; two.played++; if (a > b) { one.won++; two.lost++; one.points++; } else if (b > a) { two.won++; one.lost++; two.points++; } one.eventDiff += a - b; two.eventDiff += b - a; one.setPointDiff += diff; two.setPointDiff -= diff; }); return Object.values(rows).sort((a, b) => b.points - a.points || b.eventDiff - a.eventDiff || b.setPointDiff - a.setPointDiff); }
function StandingsTable({ rows }) { if (!rows.length) return <p className="empty-state">No teams in this group.</p>; return <div className="table-container"><table><thead><tr><th>#</th><th>Team</th><th>P</th><th>W</th><th>L</th><th>Points</th><th>Event Diff</th><th>Set Pt Diff</th></tr></thead><tbody>{rows.map((row, index) => <tr key={row.id}><td>{index + 1}</td><td><strong>{row.name}</strong></td><td>{row.played}</td><td>{row.won}</td><td>{row.lost}</td><td className="accent-value">{row.points}</td><td>{row.eventDiff > 0 ? `+${row.eventDiff}` : row.eventDiff}</td><td>{row.setPointDiff > 0 ? `+${row.setPointDiff}` : row.setPointDiff}</td></tr>)}</tbody></table></div>; }

export function SquadsPage() { const { state, page, context } = usePublicPage('Squads', 'Browse teams, owners, and players.'); if (page) return page; const { teams, auction } = details(state.data); return <PageFrame title="Squads" subtitle="Browse teams, owners, and players." context={context}>{teams.length ? <div className="squad-grid">{teams.map(team => { const listedPlayers = team.players_list || []; const auctionPlayers = auction?.team_players?.[team.id] || []; const players = [...new Map([...listedPlayers, ...auctionPlayers].map(player => { const normalized = typeof player === 'object' ? player : { name: player }; return [normalized.name, normalized]; })).values()]; return <section className="squad-card" key={team.id}><h3>{team.name}</h3>{team.owners && <p>Owner: {team.owners}</p>}<ul>{players.map(player => <li key={player.name}>{player.name}{player.gender && <span className="player-gender">{player.gender}</span>}</li>)}</ul>{!players.length && <p>No players.</p>}</section>; })}</div> : <p className="empty-state">No teams added yet.</p>}</PageFrame>; }
export function PlayerEventsPage() { const { state, page, context } = usePublicPage('Player Events', 'See events played by every player.'); const [teamId, setTeamId] = useState(''); if (page) return page; const { teams, scorecards, players, auction } = details(state.data); const selected = teamId || teams[0]?.id || ''; const team = teams.find(t => t.id === selected); const counts = {}; scorecards.forEach(score => { [['team1', score.winner === 'team1'], ['team2', score.winner === 'team2']].forEach(([side, won]) => { [score[`${side}_player1`], score[`${side}_player2`]].filter(Boolean).forEach(player => { counts[player] = counts[player] || { events: 0, wins: 0, losses: 0 }; counts[player].events++; if (won) counts[player].wins++; else if (score.winner) counts[player].losses++; }); }); }); const teamNames = new Set((team?.players_list || []).map(player => typeof player === 'object' ? player.name : player)); (auction?.team_players?.[selected] || []).forEach(player => teamNames.add(player.name)); const roster = teamNames.size ? [...teamNames] : players.map(player => player.name); return <PageFrame title="Player Events" subtitle="See events played by every player." context={context}><select className="form-input team-select" value={selected} onChange={event => setTeamId(event.target.value)}>{teams.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select>{roster.length ? <div className="table-container"><table><thead><tr><th>#</th><th>Player</th><th>Events Played</th><th>Won</th><th>Lost</th></tr></thead><tbody>{roster.map((name, i) => <tr key={name}><td>{i + 1}</td><td><strong>{name}</strong></td><td><span className="badge badge-in-progress">{counts[name]?.events || 0}</span></td><td>{counts[name]?.wins || 0}</td><td>{counts[name]?.losses || 0}</td></tr>)}</tbody></table></div> : <p className="empty-state">No players found in this team.</p>}</PageFrame>; }
export function PlayerStatsPage() { const { state, page, context } = usePublicPage('Player Stats', 'Compare player performance across events.'); if (page) return page; const { teams, scorecards } = details(state.data); const stats = {}; teams.forEach(team => (team.players_list || []).forEach(player => { const name = typeof player === 'object' ? player.name : player; stats[name] = { name, team: team.name, events: 0, wins: 0, setsWon: 0, setsLost: 0, pointDifference: 0 }; })); scorecards.forEach(score => { const sides = [['team1', score.winner === 'team1'], ['team2', score.winner === 'team2']]; sides.forEach(([side, won]) => { const players = [score[`${side}_player1`], score[`${side}_player2`]].filter(Boolean); players.forEach(name => { if (!stats[name]) stats[name] = { name, team: 'Unassigned', events: 0, wins: 0, setsWon: 0, setsLost: 0, pointDifference: 0 }; stats[name].events++; if (won) stats[name].wins++; (score.sets || []).forEach(set => { const own = set[`${side}_score`] || 0, opponent = set[side === 'team1' ? 'team2_score' : 'team1_score'] || 0; if (own > opponent) stats[name].setsWon++; if (own < opponent) stats[name].setsLost++; stats[name].pointDifference += own - opponent; }); }); }); }); return <PageFrame title="Player Stats" subtitle="Compare player performance across events." context={context}><div className="table-container"><table><thead><tr><th>#</th><th>Player</th><th>Team</th><th>Events</th><th>Wins</th><th>Sets Won</th><th>Sets Lost</th><th>Point Difference</th></tr></thead><tbody>{Object.values(stats).sort((a, b) => b.wins - a.wins || b.events - a.events).map((player, index) => <tr key={`${player.team}-${player.name}`}><td>{index + 1}</td><td><strong>{player.name}</strong></td><td>{player.team}</td><td>{player.events}</td><td className="accent-value">{player.wins}</td><td>{player.setsWon}</td><td>{player.setsLost}</td><td>{player.pointDifference > 0 ? `+${player.pointDifference}` : player.pointDifference}</td></tr>)}</tbody></table></div></PageFrame>; }
function mvpWeight(eventName = '') { const name = eventName.toLowerCase(); if (name.includes('mixed') && name.includes('doubles')) return 1.3; if (name.includes('doubles')) return 1.15; return 1; }
function calculateMvp(teams, events, scorecards) { const players = {}; teams.forEach(team => (team.players_list || []).forEach(player => { const name = typeof player === 'object' ? player.name : player; players[name] = { name, team: team.name, events: 0, wins: 0, losses: 0, pointDifference: 0, mvpPoints: 0 }; })); scorecards.filter(score => score.status === 'completed' && score.winner).forEach(score => { const event = events.find(item => item.id === score.event_id); const weight = mvpWeight(event?.name); [['team1', score.winner === 'team1'], ['team2', score.winner === 'team2']].forEach(([side, won]) => { [score[`${side}_player1`], score[`${side}_player2`]].filter(Boolean).forEach(name => { if (!players[name]) players[name] = { name, team: 'Unassigned', events: 0, wins: 0, losses: 0, pointDifference: 0, mvpPoints: 0 }; let pointDifference = 0; (score.sets || []).forEach(set => { pointDifference += (set[`${side}_score`] || 0) - (set[side === 'team1' ? 'team2_score' : 'team1_score'] || 0); }); players[name].events++; players[name].pointDifference += pointDifference; if (won) players[name].wins++; else players[name].losses++; players[name].mvpPoints += ((won ? 10 : 3) + pointDifference * 0.2) * weight; }); }); }); return Object.values(players).sort((a, b) => { const mvpDifference = b.mvpPoints - a.mvpPoints; if (Math.abs(mvpDifference) <= 0.5) return b.wins / (b.events || 1) - a.wins / (a.events || 1) || b.pointDifference - a.pointDifference; return mvpDifference; }); }
export function MvpPage() { const { state, page, context } = usePublicPage('Tournament MVP', 'Identify the most valuable player using weighted match performance.'); if (page) return page; const { teams, events, scorecards } = details(state.data); const players = calculateMvp(teams, events, scorecards); const winner = players[0]; return <PageFrame title="Tournament MVP" subtitle="Identify the most valuable player using weighted match performance." context={context}>{winner?.events ? <><section className="glass-card" style={{ marginBottom: '1.5rem', textAlign: 'center' }}><p className="eyebrow">MOST VALUABLE PLAYER</p><h2 style={{ margin: '0.25rem 0' }}>{winner.name}</h2><p style={{ color: 'var(--text-secondary)', margin: 0 }}>{winner.team} · {winner.mvpPoints.toFixed(2)} MVP points</p></section><div className="table-container"><table><thead><tr><th>#</th><th>Player</th><th>Team</th><th>MVP Points</th><th>Events</th><th>Wins</th><th>Lost</th><th>Win %</th><th>Net Diff</th></tr></thead><tbody>{players.filter(player => player.events).map((player, index) => <tr key={`${player.team}-${player.name}`}><td>{index + 1}</td><td><strong>{player.name}</strong></td><td>{player.team}</td><td className="accent-value">{player.mvpPoints.toFixed(2)}</td><td>{player.events}</td><td>{player.wins}</td><td>{player.losses}</td><td>{((player.wins / player.events) * 100).toFixed(1)}%</td><td>{player.pointDifference > 0 ? `+${player.pointDifference}` : player.pointDifference}</td></tr>)}</tbody></table></div></> : <p className="empty-state">No completed events available for MVP scoring.</p>}</PageFrame>; }
export function AuctionPage() { const { state, page, context } = usePublicPage('Live Auction', 'Follow the player auction in real time.'); if (page) return page; const { teams } = details(state.data); return <PageFrame title="Live Auction" subtitle="Follow the player auction in real time." context={context}>{state.auction ? <div className="auction-panel"><div className="auction-title"><Gavel color="var(--accent-danger)" /><h2>Live now</h2><span className="live-pill"><Activity size={12} /> LIVE</span></div><AuctionTable auction={state.auction} teams={teams} /></div> : <p className="empty-state">There is no live auction right now.</p>}</PageFrame>; }
function AuctionTable({ auction, teams }) { const [zoom, setZoom] = useState(1); const activeTeams = teams.filter(team => auction.team_players?.[team.id] !== undefined); return <><div className="zoom-controls"><button className="btn btn-outline" title="Zoom out" onClick={() => setZoom(value => Math.max(.5, value - .1))}><ZoomOut size={16} /></button><span>{Math.round(zoom * 100)}%</span><button className="btn btn-outline" title="Zoom in" onClick={() => setZoom(value => Math.min(2, value + .1))}><ZoomIn size={16} /></button></div><div className="table-container auction-scroll"><table style={{ zoom }}><thead><tr>{activeTeams.map(team => <th colSpan="3" key={team.id}>{team.name}</th>)}</tr><tr>{activeTeams.flatMap(team => [<th key={`${team.id}-n`}>No.</th>, <th key={`${team.id}-p`}>Player</th>, <th key={`${team.id}-g`}>Gender</th>])}</tr></thead><tbody>{Array.from({ length: auction.max_players || 0 }, (_, row) => <tr key={row}>{activeTeams.flatMap(team => { const player = auction.team_players[team.id]?.[row]; return [<td key={`${team.id}-n-${row}`}>{row + 1}</td>, <td key={`${team.id}-p-${row}`}>{player?.name || '-'}</td>, <td key={`${team.id}-g-${row}`}>{player ? player.gender === 'Male' ? 'M' : 'F' : '-'}</td>]; })}</tr>)}</tbody></table></div></>; }
